---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: eu-west-3
  tasks:
    - name: gather instances
      ec2_instance_facts:
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        region: "{{ region }}"
     
